name: Publish to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Check out
              uses: actions/checkout@v1

            - name: Generate your awesome content
              run: npm run build-docs

            - name: Publish generated content to GitHub Pages
              uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
              with:
                  dir: docs
                  branch: docs
                  token: ${{ secrets.GITHUB_TOKEN }}
